services:

  service1:
    image: exercise1/service2
    build:
      dockerfile: Dockerfile
      context: ./service1/
    ports:
      - 8080:8080

  service2:
      image: exercise1/service2
      build:
        dockerfile: Dockerfile
        context: ./service2/
      expose: # only needed by the backend services i.e. no need to expose to the host
        - 8081
 


