services:

  service1:
    image: exercise1/service1
    build:
      dockerfile: Dockerfile
      context: ./service1/
    ports:
      - "8199:8199"
    depends_on:
      - service2

  service2:
      image: exercise1/service2
      build:
        dockerfile: Dockerfile
        context: ./service2/
      expose: # only needed by the backend services i.e. no need to expose to the host
        - 8200
 


